### PR TITLE
fix for 64-bit chocolatey installs

### LINKED ISSUE #38: Exception installing on 2008r2 with "exit code 16389"
```
       Recipe: chocolatey::default
       
           
           ================================================================================
           Error executing action `run` on resource 'powershell_script[install chocolatey]'
           ================================================================================
           
           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           Expected process to exit with [0], but received '1'
           ---- Begin output of "powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Unrestricted -InputFormat None -File "C:/Users/vagrant/AppData/Local/Temp/chef-script20150520-1280-1e8f9ki.ps1" ----
           STDOUT: Downloading https://chocolatey.org/api/v2/package/chocolatey/ to C:\Users\vagrant\AppData\Local\Temp\chocolatey\chocInstall\chocolatey.zip
           Download 7Zip commandline tool
           Downloading https://chocolatey.org/7za.exe to C:\Users\vagrant\AppData\Local\Temp\chocolatey\chocInstall\7za.exe
           Extracting C:\Users\vagrant\AppData\Local\Temp\chocolatey\chocInstall\chocolatey.zip to C:\Users\vagrant\AppData\Local\Temp\chocolatey\chocInstall...
           
           7-Zip (A) 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18
           
           Processing archive: C:\Users\vagrant\AppData\Local\Temp\chocolatey\chocInstall\chocolatey.zip
           
           Extracting  _rels\.rels
           Extracting  chocolatey.nuspec
           Extracting  tools\chocolateyInstall.ps1
           Extracting  tools\chocolateysetup.psm1
           Extracting  tools\init.ps1
           Extracting  tools\chocolateyInstall\choco.exe
           Extracting  tools\chocolateyInstall\choco.exe.ignore
           Extracting  package\services\metadata\core-properties\61804721eec44e8592a61904d0a62022.psmdcp
           Extracting  [Content_Types].xml
           
           Everything is Ok
           
           Files: 9
           Size:       3738621
           Compressed: 1259522
           Installing chocolatey on this machine
           Downloading 'http://download.microsoft.com/download/9/5/A/95A9616B-7A37-4AF6-BC36-D6EA96C8DAAE/dotNetFx40_Full_x86_x64.exe' to 'C:\Users\vagrant\AppData\Local\Temp\dotNetFx40_Full_x86_x64.exe' - the installer is 40+ MBs, so this could take awhile on a slow connection.
           Installing 'C:\Users\vagrant\AppData\Local\Temp\dotNetFx40_Full_x86_x64.exe' - this may take awhile with no output.
           WARNING: First try of .NET framework install failed with exit code '16389'. 
           Trying again.
           Installing 'C:\Users\vagrant\AppData\Local\Temp\dotNetFx40_Full_x86_x64.exe' - this may take awhile with no output.
           STDERR: .NET Framework install failed with exit code '16389'. 
            This will cause the rest of the install to fail.Error installing .NET Framework 4.0 (exit code 16389). 
            Please install the .NET Framework 4.0 manually and then try to install Chocolatey again. 
            Download at 'http://download.microsoft.com/download/9/5/A/95A9616B-7A37-4AF6-BC36-D6EA96C8DAAE/dotNetFx40_Full_x86_x64.exe'
           ---- End output of "powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Unrestricted -InputFormat None -File "C:/Users/vagrant/AppData/Local/Temp/chef-script20150520-1280-1e8f9ki.ps1" ----
           Ran "powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Unrestricted -InputFormat None -File "C:/Users/vagrant/AppData/Local/Temp/chef-script20150520-1280-1e8f9ki.ps1" returned 1
           
           Resource Declaration:
           ---------------------
           # In C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/chocolatey/recipes/default.rb
           
            27: powershell_script 'install chocolatey' do
            28:   code "iex ((new-object net.webclient).DownloadString('#{node['chocolatey']['Uri']}'))"
            29:   convert_boolean_return true
            30:   not_if { ChocolateyHelpers.chocolatey_installed? }
            31: end
            32: 
           
           Compiled Resource:
           ------------------
           # Declared in C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/chocolatey/recipes/default.rb:27:in `from_file'
           
           powershell_script("install chocolatey") do
             action "run"
             retries 0
             retry_delay 2
             default_guard_interpreter :powershell_script
             command "install chocolatey"
             backup 5
             returns 0
             code "iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1'))"
             interpreter "powershell.exe"
             convert_boolean_return true
             declared_type :powershell_script
             cookbook_name "chocolatey"
             recipe_name "default"
             not_if { #code block }
           end
           
       
       Running handlers:
       [2015-05-20T12:08:36-07:00] ERROR: Running exception handlers
       Running handlers complete
       [2015-05-20T12:08:36-07:00] ERROR: Exception handlers complete
       [2015-05-20T12:08:36-07:00] FATAL: Stacktrace dumped to C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/chef-stacktrace.out
       Chef Client failed. 0 resources updated in 80.3125 seconds
       [2015-05-20T12:08:36-07:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: powershell_script[install chocolatey] (chocolatey::default line 27) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
       ---- Begin output of "powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Unrestricted -InputFormat None -File "C:/Users/vagrant/AppData/Local/Temp/chef-script20150520-1280-1e8f9ki.ps1" ----
       STDOUT: Downloading https://chocolatey.org/api/v2/package/chocolatey/ to C:\Users\vagrant\AppData\Local\Temp\chocolatey\chocInstall\chocolatey.zip
       Download 7Zip commandline tool
       Downloading https://chocolatey.org/7za.exe to C:\Users\vagrant\AppData\Local\Temp\chocolatey\chocInstall\7za.exe
       Extracting C:\Users\vagrant\AppData\Local\Temp\chocolatey\chocInstall\chocolatey.zip to C:\Users\vagrant\AppData\Local\Temp\chocolatey\chocInstall...
       
       7-Zip (A) 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18
       
       Processing archive: C:\Users\vagrant\AppData\Local\Temp\chocolatey\chocInstall\chocolatey.zip
       
       Extracting  _rels\.rels
       Extracting  chocolatey.nuspec
       Extracting  tools\chocolateyInstall.ps1
       Extracting  tools\chocolateysetup.psm1
       Extracting  tools\init.ps1
       Extracting  tools\chocolateyInstall\choco.exe
       Extracting  tools\chocolateyInstall\choco.exe.ignore
       Extracting  package\services\metadata\core-properties\61804721eec44e8592a61904d0a62022.psmdcp
       Extracting  [Content_Types].xml
       
       Everything is Ok
       
       Files: 9
       Size:       3738621
       Compressed: 1259522
       Installing chocolatey on this machine
       Downloading 'http://download.microsoft.com/download/9/5/A/95A9616B-7A37-4AF6-BC36-D6EA96C8DAAE/dotNetFx40_Full_x86_x64.exe' to 'C:\Users\vagrant\AppData\Local\Temp\dotNetFx40_Full_x86_x64.exe' - the installer is 40+ MBs, so this could take awhile on a slow connection.
       Installing 'C:\Users\vagrant\AppData\Local\Temp\dotNetFx40_Full_x86_x64.exe' - this may take awhile with no output.
       WARNING: First try of .NET framework install failed with exit code '16389'. 
       Trying again.
       Installing 'C:\Users\vagrant\AppData\Local\Temp\dotNetFx40_Full_x86_x64.exe' - this may take awhile with no output.
       STDERR: .NET Framework install failed with exit code '16389'. 
        This will cause the rest of the install to fail.Error installing .NET Framework 4.0 (exit code 16389). 
        Please install the .NET Framework 4.0 manually and then try to install Chocolatey again. 
        Download at 'http://download.microsoft.com/download/9/5/A/95A9616B-7A37-4AF6-BC36-D6EA96C8DAAE/dotNetFx40_Full_x86_x64.exe'
       ---- End output of "powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Unrestricted -InputFormat None -File "C:/Users/vagrant/AppData/Local/Temp/chef-script20150520-1280-1e8f9ki.ps1" ----
       Ran "powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Unrestricted -InputFormat None -File "C:/Users/vagrant/AppData/Local/Temp/chef-script20150520-1280-1e8f9ki.ps1" returned 1
>>>>>> Converge failed on instance <default-windows-2008r2-standard>.
>>>>>> Please see .kitchen/logs/default-windows-2008r2-standard.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: WinRM exited (1) for command: [
$env:PATH = [System.Environment]::GetEnvironmentVariable("PATH","Machine")

& $env:systemdrive\opscode\chef\bin\chef-client.bat --local-mode --config $env:TEMP\kitchen\client.rb --log_level auto --force-formatter --no-color --json-attributes $env:TEMP\kitchen\dna.json --chef-zero-port 8889]
```

Unsure of where to go with this one but neither this repo or the chocolatey repo have an issue that matches this exit code, open or closed.

### PR DESCRIPTION
**Pull request by lamont-granquist**
on 64-bit we need to invoke the install in a 64-bit environment.

we can use the interpreter flag to the chef script resource to do this.

i had a dificult time beating powershell_script into submission.  invoking cmd
to invoke powershell is a little gross, but the full path to the 64-bit
cmd.exe also looks like it'll be less brittle than the powershell path that
had the version string embedded in it.

fixes #38

### CODE REVIEW

File: recipes/default.rb [hunk 1]
```diff
@@ -24,10 +24,21 @@
 # ::Chef::Recipe.send(:include, Chef::Mixin::PowershellOut)
 ::Chef::Resource::RubyBlock.send(:include, Chef::Mixin::PowershellOut)
 
-powershell_script 'install chocolatey' do
-  code "iex ((new-object net.webclient).DownloadString('#{node['chocolatey']['Uri']}'))"
-  convert_boolean_return true
-  not_if { ChocolateyHelpers.chocolatey_installed? }
+if File.exist?('C:\windows\system32\cmd.exe')
+  arch = :x86_64
+  cmd = 'C:\windows\system32\cmd.exe'
```
Comment (ferventcoder) [inline recipes/default.rb]: On a 32 bit system the path `C:\windows\system32\cmd.exe` is going to exist, which means this will always set arch to `:x86_64`.

I would use something more deterministic for setting the architecture.

On the whole, you should look for the existence of `c:\Windows\sysnative\cmd.exe`, which is going to tell you that you have a 32 bit process on a 64 bit system and SysWOW64 is in play.

Comment (lamont-granquist) [inline recipes/default.rb]: Okay, yeah I was going to update this that I had some questions around it.

What if someone has installed chef on their own 64-bit ruby (although technically this is not something we support) and so we're invoking from a 64-bit process on a 64-bit system?  Will the sysnative path still exist and still point at 64-bit?

Comment (ferventcoder) [inline recipes/default.rb]: No it doesn't exist outside of syswow64. I think it will need additional checks for architecture that are more deterministic, but consider the following:

The only time you need to make choco do something different is when syswow64 is at play, the other times it will just work as intended.

File: recipes/default.rb [hunk 2]
```diff
@@ -24,9 +24,20 @@
...
+else
+  arch = nil
+  cmd = 'cmd.exe'
+end
+
+batch 'install chocolatey' do
+  architecture arch
+  interpreter cmd
+  code <<-EOH
+    powershell -noprofile -inputformat none -noninteractive -executionpolicy bypass -command "iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1'))"
```
Comment (ferventcoder) [inline recipes/default.rb]: This seems to have removed `#{node['chocolatey']['Uri']}`, which I might imagine is still important?

File: recipes/default.rb (hunk 1 above)
Comment (lamont-granquist) [inline recipes/default.rb]: Okay so does that logic look good as is then, and just let cmd.exe DTRT through the Path env?

Comment (ferventcoder) [inline recipes/default.rb]: DTRT?

Comment (lamont-granquist) [inline recipes/default.rb]: Do The Right Thing

Comment (ferventcoder) [inline recipes/default.rb]: The logic of detecting sysnative and forcing x64 versus just letting it do what it normally would looks fine to me. :)

**Comment by lamont-granquist** [comment]
Okay unless there's some more derp I left in, I think this should be shippable...

File: recipes/default.rb (hunk 1 above)
Comment (ferventcoder) [inline recipes/default.rb]: Should be fine otherwise. Although you could add an additional check for `c:\windows\system32\cmd.exe`, but I don't think that is necessary here.

Comment (lamont-granquist) [inline recipes/default.rb]: Yeah, it feels like that would be additional complication that would only add possibly unintended consequences...    This now reads like the logic in my brain which is `if we're doing SysWOW64 stuff then special case it, otherwise just let it run normally....`

Comment (ferventcoder) [inline recipes/default.rb]: Yup. ;)

**Comment by ferventcoder** [comment]
@guilhem @mwrock this looks ready for you to look over

**Comment by mwrock** [comment]
I think this looks good. I wouldn't worry too much about the '1.0' in the powershell path although it does seem weird. I have a feeling it will always be there or at least redirect.

But if the `powershell_script` is not working then this is definitely the right approach. Even if you could get it to work, I think this is fine.

**Comment by lamont-granquist** [comment]
Ah okay, well I tried to hammer on powershell_script with different interpreter paths and architectures and didn't get it to work while this does...
